version: "2"
volumes:
  database-data:
services:
  docker-ecosystem-java-service:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-java-service:${IMAGE_VERSION}
    ports:
      - '4567:4567'
    build: .
    links:
      - database
    depends_on:
      - migration
  migration:
    image: ${IMAGE_REGISTRY}/docker-ecosystem-migration
    links:
      - database
  database:
    image: postgres:9.5.1
    volumes:
      - database-data:/var/lib/postgres/data
