version: "2"
volumes:
  database-data:
services:
  docker-ecosystem-java-service:
    image: ${REGISTRY_HOST}/docker-ecosystem-java-service:${IMAGE_TAG}
    ports:
      - "4567"
    build: .
    links:
      - database
    depends_on:
      - migration
  migration:
    image: ${REGISTRY_HOST}/docker-ecosystem-migration
    links:
      - database
  database:
    image: postgres:9.5.1
    volumes:
      - database-data:/var/lib/postgres/data
